### ISSUE TITLE
Ability to set/recognize user alias

### ISSUE THREAD

**Issue by kengz** [github/hubot#1022]
It's be useful if hubot can remember and recognize alias for a user, say, **coolguy123** as _James_, so calling _"hubot tell James to foo"_ makes sense.

**Comment by technicalpickles** [comment]
This one is a bit interesting. To support this, you'd need (at least off hand):

* a command to set an alias (it'd just lookup the user, and append to the user object in the brain)
* a way to query the brain for alias or a username

Querying the brain is easy, but the problem with a script is... hubot itself doesn't have any scripts. If you generate a new bot, sure you get a few default scripts, but this is a case where there's some built in functionality that expects you to use a specific script. I'd have to think about that a bit.

That aside, scripts would need to be updated specifically to use it. That is probably not an issue. `robot.brain.userForAlias` or something like that. But then, you'd probably want to support looking up by name or alias, so `robot.brain.userForAliasOrName`. At that point, now we have some user experience problems with setting alias, since I could make an alias like kengz, so anyone that `hubot tell kengz to foo` goes to me instead of you.

Like I said, it's interesting, but needs some more consideration about how it'd work in practice.

**Comment by kengz** [comment]
I've attempted to implement a solution outside of hubot's core, and have been using it. That's why I was referring this from the issue cited above.

[screenshot of usage here](https://github.com/kengz/jarvis#alias)

**Comment by technicalpickles** [comment]
@kengz do you have any thoughts about possible confusion I was talking about here?

> That aside, scripts would need to be updated specifically to use it. That is probably not an issue. `robot.brain.userForAlias` or something like that. But then, you'd probably want to support looking up by name or alias, so `robot.brain.userForAliasOrName`. At that point, now we have some user experience problems with setting alias, since I could make an alias like kengz, so anyone that `hubot tell kengz to foo` goes to me instead of you.

**Comment by kengz** [comment]
Hello @technicalpickles sorry I was away.

Yes regarding the ambiguity in user aliases; it's resolved by having an order of preference: ranked phonetically, ordered from username, then its aliases.

**Comment by technicalpickles** [comment]
I'm still having a hard time thinking about this in hubot by default. I think ideally, it'd be a nice extension, but we don't have a great pattern for extensions yet :sweat: 

If we had something like https://github.com/github/hubot/issues/858 I think that would make it easier for people to change more underlying hubot behavior like this.
